### ISSUE TITLE
Visa letter needed - Daniel Phiri

### ISSUE THREAD

**Issue by bdemott** [github/git-merge#180]
This is for one of our speakers at Git Merge. @haleygirl Could you help get him a letter for his Visa. Thanks!!!

First Name:  Daniel  
Last Name:  Phiri  
Date of Birth: 02/12/1997
Place of Birth: Lusaka, Zambia
Passport No:  ZN479217  
Country:  Zambia

**Comment by amcano** [comment]
[Git Mege Travel Invite.pdf](https://github.com/github/git-merge/files/2626110/Git.Mege.Travel.Invite.pdf)

@haleygirl Please let me know if there is anything else you need from me! Thank you!

**Comment by haleygirl** [comment]
@amcano thanks!
