### ISSUE TITLE
Free marketing on FOSDEM fringe page 

### ISSUE THREAD

**Issue by haleygirl** [github/git-merge#182]
@AlaineN @bdemott @kcpike 

I got this note from a helpful citizen :) in Halp:

> You have forgotten to tell FOSDEM to add this to the Fringe-page, that
is how I found you the first time. https://fosdem.org/2019/fringe/

We can add Git Merge information free & easily here: https://submission.fosdem.org/fringe.php

I didn't want to fill it out in case there was specific information we want to share like "Git Merge 2019 - use GM19FOSDEM50 for discount". The copy made available to attendees is limited on this site.

**Comment by AlaineN** [comment]
Thanks @haleygirl ! I filled out the page for Fringe.
