### ISSUE TITLE
Visa letter needed - Tanushree Tumane

### ISSUE THREAD

**Issue by peff** [github/git-merge#184]
@haleygirl This is one of Git's Outreachy interns, who will be coming to the contributor summit and to the main conference.

First Name: Tanushree
Last Name: Tumane
Date of Birth:15-01-1996
Place of Birth: Nagpur City
Passport No: J7130216
Country: India

**Comment by haleygirl** [comment]
@peff you got it.

@amcano - 👋 hello, can you please assist with a letter and mention me when complete? Thanks!

First Name: Tanushree
Last Name: Tumane
Date of Birth:15-01-1996
Place of Birth: Nagpur City
Passport No: J7130216
Country: India

**Comment by amcano** [comment]
[Git Mege Travel Invite Tanushree Tumane.pdf](https://github.com/github/git-merge/files/2687472/Git.Mege.Travel.Invite.Tanushree.Tumane.pdf)

@haleygirl the letter is attached. Please let me know if there is anything else you need. Thanks!

**Comment by haleygirl** [comment]
Thanks @amcano

**Comment by peff** [comment]
Thanks, I've passed it along to Tanushree.
