### ISSUE TITLE
Git Merge Visa Letter - Aniket Kadam

### ISSUE THREAD

**Issue by bdemott** [github/git-merge#185]
@amcano Hello! I have another speaker who is in need of a Visa letter. Since we are running up against the holidays it would be awesome if I could get this by the end of the week.

First Name: Aniket
Last Name: Kadam
Date of Birth: 12/08/1987
Place of Birth: Mumbai, Maharashtra
Passport Number: Z2202317
Country: India

**Also, his country requires that the dates of his stay are in the letter. He is going to be in Brussels the 30th January to the 10th February.**

The event information is as follows:

GitHub hosted event, Git Merge.
Date: February 1st
Venue: The EGG Brussels, Rue Bara 175, 1070 Bruxelles, Belgium
City, Country: Brussels Belgium
QTY: 350 attendees
Event Site: https://git-merge.com/

### Blurb

Git Merge is a one-day conference (with an add-on Workshop Day) dedicated to the version control tool that started it all—and the people who use it every day. From technical sessions to hands-on workshops, developers of all experience levels will find new ways to use, build on, and scale Git on their teams.

This event is dedicated to amplifying new voices in the Git community and to showcasing the most thought-provoking projects from contributors, maintainers and community managers around the world.

### Photos

A few photos of his passport 🤷‍♂️ 

![back1](https://user-images.githubusercontent.com/8631813/50252864-3ffffa80-039d-11e9-91cc-6ed908b399cc.jpg)
![front1](https://user-images.githubusercontent.com/8631813/50252865-40989100-039d-11e9-8ee6-303038d7aaea.jpg)

**Comment by amcano** [comment]
@bdemott Visa letter is complete, including travel dates! Please let me know if anything else is needed. Thank you! 
[Git Mege Travel Invite Aniket Kadam.pdf](https://github.com/github/git-merge/files/2699956/Git.Mege.Travel.Invite.Aniket.Kadam.pdf)

**Comment by bdemott** [comment]
Thanks!!!!! ❤️
